name: Trigger auto deployment for wapp02

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/wapp02-AutoDeployTrigger-d7ee401e-fac6-4df9-80d3-54f6b3d4a714.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.WAPP02_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WAPP02_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WAPP02_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.WAPP02_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WAPP02_REGISTRY_PASSWORD }}
          containerAppName: wapp02
          resourceGroup: RGTEST
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


